import type { Metadata } from 'next'
import './globals.css'
import { SwiperProvider } from '@/lib/context'
import { dmSans } from '@/lib/font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <link
          href='https://fonts.googleapis.com/css2?family=Paytone+One&display=swap'
          rel='stylesheet'
        />
      </head>
      <body className={`${dmSans.variable} antialiased`}>
        <SwiperProvider>{children}</SwiperProvider>
      </body>
    </html>
  )
}